# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule DatabaumLeafWetnessAPI(Dev).Model.HttpValidationError do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"errors"
  ]

  @type t :: %__MODULE__{
    :"errors" => [DatabaumLeafWetnessAPI(Dev).Model.ValidationError.t] | nil
  }
end

defimpl Poison.Decoder, for: DatabaumLeafWetnessAPI(Dev).Model.HttpValidationError do
  import DatabaumLeafWetnessAPI(Dev).Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"errors", :list, DatabaumLeafWetnessAPI(Dev).Model.ValidationError, options)
  end
end

