# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule DatabaumLeafWetnessAPI(Dev).Model.Location do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"lon",
    :"lat"
  ]

  @type t :: %__MODULE__{
    :"lon" => float(),
    :"lat" => float()
  }
end

defimpl Poison.Decoder, for: DatabaumLeafWetnessAPI(Dev).Model.Location do
  def decode(value, _options) do
    value
  end
end

