# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule DatabaumLeafWetnessAPI(Dev).Model.TokenResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"access_token",
    :"token_type"
  ]

  @type t :: %__MODULE__{
    :"access_token" => String.t,
    :"token_type" => String.t
  }
end

defimpl Poison.Decoder, for: DatabaumLeafWetnessAPI(Dev).Model.TokenResponse do
  def decode(value, _options) do
    value
  end
end

