# NOTE: This file is auto generated by OpenAPI Generator 6.1.1-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DatabaumLeafWetnessAPI.Model.HttpValidationError do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :errors
  ]

  @type t :: %__MODULE__{
    :errors => [DatabaumLeafWetnessAPI.Model.ValidationError.t] | nil
  }
end

defimpl Poison.Decoder, for: DatabaumLeafWetnessAPI.Model.HttpValidationError do
  import DatabaumLeafWetnessAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:errors, :list, DatabaumLeafWetnessAPI.Model.ValidationError, options)
  end
end

