# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule DatabaumLeafWetnessAPI.Model.LeafWetnessMeasurement do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"datetime",
    :"leaf_wetness"
  ]

  @type t :: %__MODULE__{
    :"datetime" => DateTime.t,
    :"leaf_wetness" => integer()
  }
end

defimpl Poison.Decoder, for: DatabaumLeafWetnessAPI.Model.LeafWetnessMeasurement do
  def decode(value, _options) do
    value
  end
end

