# NOTE: This file is auto generated by OpenAPI Generator 6.1.1-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DatabaumLeafWetnessAPI.Model.TokenResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :access_token,
    :token_type
  ]

  @type t :: %__MODULE__{
    :access_token => String.t,
    :token_type => String.t
  }
end

defimpl Poison.Decoder, for: DatabaumLeafWetnessAPI.Model.TokenResponse do
  def decode(value, _options) do
    value
  end
end

