# NOTE: This file is auto generated by OpenAPI Generator 6.1.1-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DatabaumLeafWetnessAPI.Model.UserResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :email
  ]

  @type t :: %__MODULE__{
    :id => integer(),
    :email => String.t
  }
end

defimpl Poison.Decoder, for: DatabaumLeafWetnessAPI.Model.UserResponse do
  def decode(value, _options) do
    value
  end
end

