# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule DatabaumLeafWetnessAPI.Model.UserResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"email"
  ]

  @type t :: %__MODULE__{
    :"id" => integer(),
    :"email" => String.t
  }
end

defimpl Poison.Decoder, for: DatabaumLeafWetnessAPI.Model.UserResponse do
  def decode(value, _options) do
    value
  end
end

