# NOTE: This file is auto generated by OpenAPI Generator 6.1.1-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DatabaumLeafWetnessAPI.Model.ValidationError do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :loc,
    :msg,
    :type
  ]

  @type t :: %__MODULE__{
    :loc => [DatabaumLeafWetnessAPI.Model.Location1Inner.t],
    :msg => String.t,
    :type => String.t
  }
end

defimpl Poison.Decoder, for: DatabaumLeafWetnessAPI.Model.ValidationError do
  import DatabaumLeafWetnessAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:loc, :list, DatabaumLeafWetnessAPI.Model.Location1Inner, options)
  end
end

